### ISSUE TITLE
let's add side-by-side with "official" protobuf marshaling

### ISSUE THREAD

**Issue by DmitriyMV** [siderolabs/protoenc#2]
> let's add side-by-side with "official" protobuf marshaling
> _Originally posted by @smira in https://github.com/siderolabs/protoenc/pull/1#pullrequestreview-1048025699_

## Task

We should ensure that our encoder/decoder works with binary data and structs produced by official protobuf compiler. For that each test should basically contain the following.

1. Marshal Go structs to binary form using our own Marshaller
2. Unmarshal binary form into generated Go structs compiled by `protobuf` from proto messages using `proto.Unmarshal`
3. Ensure that fields in two structs match.
4. Encode resulting generated Go structs back to binary form using `proto.Marshal`
5. Unmarshal binary form into original Go structs using our own Unmarshaller.
6. Ensure that resulting struct match the original one from the stage 1.

The following test cases should be implemented:
- [x] Messages with simple fields.
- [x] Messages with repeated simple fields.
- [x] Messages with maps of simple fields.
- [x] Messages containing a map where the key is a simple type and the value is a message that contains variations of the above.
- [x] Complex messages with inner messages which contain either maps or repeated fields or both in various forms.

`anyof` and to lesser extent `enum` are not supported for now.

## Questions

- [x] Does kres support code generation for protobuf messages that are not attached to GRPC methods?
